Repository Andy-Shin99/pythonProject, pull requests merged in 2023-11, with the labels that each got.

#3 :sparkles: 무한스크롤 데이터 크롤링 구현
  infinite_scroll_data.py
Labels: New Feature

#4 :sparkles: 기간, 개수 설정 및 csv파일 저장 코드 추가
  .DS_Store
  infinite_scroll_data.py
Labels: New Feature

#5 함수 모듈화 및 디렉토리 구조 수정
  .gitignore
  datas/post_datas.py
  infinite_scroll_data.py
  utils/get_api.py
  utils/infinite_scroll_data.py
Labels: Refactor

#6 Data processing
  .DS_Store
  dics/stopwordsKor.txt
  dics/user_dic.txt
  modules/data_processing.py
  modules/infinite_scroll_data.py
  modules/post_data.py
  results/corpus_data/20160101to20161231.txt
  results/corpus_data/20170101to20171231.txt
  results/corpus_data/20180101to20181231.txt
  results/corpus_data/20190101to20191231.txt
  results/corpus_data/20200101to20201231.txt
  results/corpus_data/20210101to20211231.txt
  results/corpus_data/20220101to20221231.txt
  results/corpus_data/20230101to20231110.txt
  results/des_results/2016.txt
  results/des_results/2017.txt
  results/des_results/2018.txt
  results/des_results/2019.txt
  results/des_results/2020.txt
  results/des_results/2021.txt
  results/des_results/2022.txt
  results/des_results/2023.txt
  results/title_results/2016.txt
  results/title_results/2017.txt
  results/title_results/2018.txt
  results/title_results/2019.txt
  results/title_results/2020.txt
  results/title_results/2021.txt
  results/title_results/2022.txt
  results/title_results/2023.txt
  results/topic_modeling_results/2016.html
  results/topic_modeling_results/2017.html
  results/topic_modeling_results/2018.html
  results/topic_modeling_results/2019.html
  results/topic_modeling_results/2020.html
  results/topic_modeling_results/2021.html
  results/topic_modeling_results/2022.html
  results/topic_modeling_results/2023.html
  utils/get_api.py
  utils/infinite_scroll_data.py
Labels: New Feature

#7 Data processing
  modules/get_gephi.py
  results/graphml_results/2016.PNG
  results/graphml_results/2016.graphml
  results/graphml_results/2017.PNG
  results/graphml_results/2017.graphml
  results/graphml_results/2018.PNG
  results/graphml_results/2018.graphml
  results/graphml_results/2019.PNG
  results/graphml_results/2019.graphml
  results/graphml_results/2020.PNG
  results/graphml_results/2020.graphml
  results/graphml_results/2021.PNG
  results/graphml_results/2021.graphml
  results/graphml_results/2022.PNG
  results/graphml_results/2022.graphml
  results/graphml_results/2023.PNG
  results/graphml_results/2023.graphml
  results/graphml_results/total.gephi
  results/title_results_new/2016.txt
  results/title_results_new/2017.txt
  results/title_results_new/2018.txt
  results/title_results_new/2019.txt
  results/title_results_new/2020.txt
  results/title_results_new/2021.txt
  results/title_results_new/2022.txt
  results/title_results_new/2023.txt
  results/total_results/results.txt
Labels: New Feature

#9 연도별 여행지 그래프 구현 및 코드 디렉토리 정리
  .gitignore
  results/title_dataframes/2016.csv
  results/title_dataframes/2017.csv
  results/title_dataframes/2018.csv
  results/title_dataframes/2019.csv
  results/title_dataframes/2020.csv
  results/title_dataframes/2021.csv
  results/title_dataframes/2022.csv
  results/title_dataframes/2023.csv
  visualization/description_data.py
  visualization/destination_chart.py
  visualization/title_data.py
Labels: New Feature, Refactor
